### ISSUE TITLE
How to get departure/arrival times given an airport code?

### ISSUE THREAD

**Issue by E3V3A** [mkorkmaz/flightradar24#1]
I'd like to get the departure/arrival times given an airport code?
Is that possible? (If, not, will it be implemented?)

**Comment by mkorkmaz** [comment]
Hi @E3V3A 

Using this library it is not possible right now. But I can tell you the steps to get the data you want. May be I will implement this feature in the future. Anyway, the url below gives the list of statuses of planes at an airport.
```
https://api.flightradar24.com/common/v1/airport.json?code=ist&plugin[]=&plugin-setting[schedule][mode]=&plugin-setting[schedule][timestamp]=1515197092&page=1&limit=100&token=
```

In this case airport is Istanbul Atatürk Airport. You can see the part **'code=ist'**,  '**ist'** is IATA code of Istanbul Atatürk Airport. There is a pagination, you can see. Page items limit is **100**. 100 is maximum number can be set by the way. You can get all the pages by incrementing the page numbers. and finally use current timestamp (for GMT+0).

The list of the data you are looking for is under the ['result']['response']['airport']['pluginData']['schedule'].
