### ISSUE TITLE
usage is not clear for me, new in python

### ISSUE THREAD

**Issue by filipdns** [mkorkmaz/flightradar24#4]
hello, I'm trying to understand the usage of your project but I don't know how and where I have to do the call...

I'm under windows 10 and often work with qt, I want to include your project inside mine.

when you say:
import flightradar24
flight_id = 'TK1' # Turkish Airlines' Istanbul - New York flight
fr = flightradar24.Api()
flight = fr.get_flight(flight_id)

what I have to do exactly?...

thanks a lot for your help

**Comment by mkorkmaz** [comment]
This example just returns flights data of TK1 which displayed on the page : https://www.flightradar24.com/data/flights/tk1

This data may include scheduled flights, past flights, or current flight if the flight is live at that point.
