### ISSUE TITLE
Being Careful

### ISSUE THREAD

**Issue by GeorgeBarlow** [mkorkmaz/flightradar24#6]
Hey, 

This sounds obvious but just want people to know the datafeeds used in this project are highly monitored and if used, could lead to prosecution.

Stated by flightradar24.com: "The contents of this file and all derived data are the property of Flightradar24 AB for use exclusively by its products and applications. Using, modifying or redistributing the data without the prior written permission of Flightradar24 AB is not allowed and may result in prosecutions."

Please understand what this entails, as you already do, it may not be worth the risk.

Regards,
George

**Comment by mkorkmaz** [comment]
Thanks for the warning George. See the section below which exists on the readme file of this project:

```If you want to use the data collected using this library commercially, You need to subscribe to Business Plan. See details at https://www.flightradar24.com/premium/```

This library gives people enough playground data to get familiar with the flight data. But I strongly recommend not to use this library in other contexts.

**Comment by BarryPSmith** [comment]
Looking at https://www.flightradar24.com/premium/ I see no mention that the business plan allows automated or API access. Has this changed since 2019, or can you share where you got the information that a business plan is sufficient?

**Comment by mkorkmaz** [comment]
Hi @BarryPSmith 

Business plan allows you to access detailed information. I don't really know is there an API that FR provided for businies or premium customers. This API basically mimics websites frontend client programmatically. If your subscription allows more and detailed data, then this API can be extended to use that data. This library does not courage people to use this library for commercial purposes.
